// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF1Xlr9rk3qfc0Be3JQVRlHjxynpe6Wdo',
    appId: '1:168480091349:android:1c32c56a9afbe24db9065c',
    messagingSenderId: '168480091349',
    projectId: 'donateer-e69f9',
    storageBucket: 'donateer-e69f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhlP-8v_TL8GrcBYYmaooWxjeFINTmesg',
    appId: '1:168480091349:ios:378ffff2ab2708b6b9065c',
    messagingSenderId: '168480091349',
    projectId: 'donateer-e69f9',
    storageBucket: 'donateer-e69f9.appspot.com',
    iosClientId: '168480091349-qt7q1ldjnff3cpeurrcur5kstvmqjlp7.apps.googleusercontent.com',
    iosBundleId: 'com.example.donateer',
  );
}
